name: Upload a new release
on:
  push:
    tags:
      - "v*" #Napptive uses Semantic Versioning with the prefix 'v'

jobs:
  gh:
    name: Create GitHub Release Asset
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Make release
        id: make_release
        run: make release
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          TARGET_DOCKER_REGISTRY: napptive
          TARGET_K8S_NAMESPACE: napptive

      # Create release and upload release assets
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: "./build/*.tar.gz"

  docker:
    name: Push Docker Release Images
    runs-on: ubuntu-22.04

    needs: gh
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push Docker images
        run: make docker-push
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          TARGET_DOCKER_REGISTRY: napptive
